###

GET  http://localhost:8000
Accept : application/json

###

POST http://localhost:8000
Accept : application/json
Content-Type : application/json

{
  "text":"ryugen"
}

###

PUT http://localhost:8000
Accept : application/json
Content-Type : application/json

{
  "id":1,
  "text":"gen"
}

###

DELETE http://localhost:8000
Accept : application/json

{
    "id":1
}


